#!/bin/bash

# Script per configurar Gradle i compilar l'APK de TrobaCar

echo "=== Configuració de TrobaCar ==="
echo ""

# Crear directori gradle/wrapper si no existeix
mkdir -p gradle/wrapper

# Descarregar Gradle wrapper
echo "Descarregant Gradle wrapper..."
GRADLE_VERSION="8.2"
GRADLE_DIST_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"

# Crear gradle-wrapper.properties
cat > gradle/wrapper/gradle-wrapper.properties << EOF
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=${GRADLE_DIST_URL}
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
EOF

echo "Gradle wrapper configurat!"
echo ""

# Crear gradlew executable
echo "Creant gradlew..."
cat > gradlew << 'EOF'
#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \"-Dorg.gradle.appname=$APP_BASE_NAME\" -classpath \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain \"$@\"
EOF

chmod +x gradlew

echo "gradlew creat!"
echo ""
echo "=== Instruccions per compilar l'APK ==="
echo ""
echo "NOTA: Aquest script requereix Android SDK instal·lat."
echo ""
echo "Opcions per compilar:"
echo ""
echo "1. Amb Android Studio (RECOMANAT):"
echo "   - Obre el projecte TrobaCar a Android Studio"
echo "   - Build > Generate Signed Bundle/APK"
echo "   - Selecciona APK i segueix les instruccions"
echo ""
echo "2. Des de la línia de comandes:"
echo "   export ANDROID_HOME=/path/to/android-sdk"
echo "   ./gradlew assembleRelease"
echo "   # L'APK es generarà a: app/build/outputs/apk/release/"
echo ""
echo "3. APK de debug (sense signar):"
echo "   ./gradlew assembleDebug"
echo "   # L'APK es generarà a: app/build/outputs/apk/debug/"
echo ""
echo "Si no tens Android SDK:"
echo "   - Descarrega Android Studio: https://developer.android.com/studio"
echo "   - O descarrega Android Command Line Tools"
echo ""
EOF

chmod +x setup_gradle.sh

echo "Script setup_gradle.sh creat!"
echo ""
echo "Executa: ./setup_gradle.sh"
